### ISSUE TITLE
Positivity check dtheta

### ISSUE THREAD

**Issue by jchylik** [classmodel/modelgui#8]
During the calculation, dtheta can accidentally end up negative, which leads to further un-physical results. 

This can particularly when we start with strong surface forcing and relative small dtheta.

The reason is that calculations of dtheta do not currently include a check for positivity:

_model.cpp line 650_ 
`thetatend   = (wtheta + wthetae - wthetaM)  / h + advtheta;`
_line 655:_
`dthetatend  = gammatheta * (we + wf - M) - thetatend  + C_thetaft;`
_line 804:_
`dtheta   = dtheta0 + dt * dthetatend;`

The quick fix would be to check whether
`dtheta   = max(0, dtheta0 + dt * dthetatend);`

The proper fix would be a conditional block that in case of a small dtheta estimates encroachments instead.

**Comment by julietbravo** [comment]
Hi Jan, thanks for reporting the issue. There is a check for encroachment conditions, but only if you start the model in those conditions (i.e. `dthetav == 0 && beta == 0`). But there should indeed be some kind of guard against `dthetav < 0`.

Can you share a case which reproduces the problem? I just tried it myself, but starting the model from a very small `dtheta` just results in a large `dh/dt`, which then rapidly increases `dtheta` and `dthetav`.

**Comment by jchylik** [comment]
Thank you for the response! 

> Can you share a case which reproduces the problem? 
of course, it is enough to just set `dtheata0 = 0.11`
![low_dtheta](https://user-images.githubusercontent.com/49030099/199989005-cced01ae-01f0-4038-88db-1c822ce63652.png)

> but only if you start the model in those conditions (i.e. dthetav == 0 && beta == 0).
I have tried that as well, but then all outputs end at after the first step.

I have already coded an update to fix that, so I will bit refine in and post it.

**Comment by julietbravo** [comment]
Can you share the exported case in which you see this problem? I still can't reproduce it with the default case, and `dtheta0` set to `0.11` (or any other small number).

**Comment by jchylik** [comment]
> Can you share the exported case in which you see this problem? 

Of course.
I just took the default case and change the initial temperature jump to  0.11 [K] :
[setup_dtheta011.mxl](https://github.com/classmodel/modelgui/files/12714193/setup_dtheta011.mxl.txt "setup MXL file with added txt extension")

The profile output looks rather horrifying:
![profiles_dtheta011](https://github.com/classmodel/modelgui/assets/49030099/137b6dff-a1fc-4a5e-af1c-e5a2ec30cea6)

**Comment by julietbravo** [comment]
The initial `dthetav` is smaller than zero, so this is not surprising. I will continue the discussion in your PR.

**Comment by bartvstratum** [comment]
https://github.com/classmodel/modelgui/pull/11
PR has been closed after some discussion.
